rvm:
  - 1.9.3

branches:
  only:
    - master

env: DB=postgres

before_script:
  - psql -c 'create database emonweb_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:schema:load RAILS_ENV=test

script: "bundle exec rake spec"