require File.dirname(__FILE__) + '/../../../spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Api::V1::InputsController do

  # This should return the minimal set of attributes required to create a valid
  # Input. As you add validations to Input, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { 
      :name => 'power',
      :last_value => 252.4,
    }
  end

  before(:each) do
    @user = Factory(:user)
    sign_in @user
  end

  describe "GET index" do
    it "assigns all api_v1_inputs as @api_v1_inputs" do
      input = Input.create! valid_attributes
      get :index
      assigns(:inputs).should eq([input])
    end
  end

  describe "GET show" do
    it "assigns the requested input as @input" do
      input = Input.create! valid_attributes
      get :show, :id => input.id.to_s
      assigns(:input).should eq(input)
    end
  end

  describe "GET new" do
    it "assigns a new input as @input" do
      get :new
      assigns(:input).should be_a_new(Input)
    end
  end

  describe "GET edit" do
    it "assigns the requested input as @input" do
      input = Input.create! valid_attributes
      get :edit, :id => input.id.to_s
      assigns(:input).should eq(input)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Input" do
        expect {
          post :create, :input => valid_attributes
        }.to change(Input, :count).by(1)
      end

      it "assigns a newly created input as @input" do
        post :create, :input => valid_attributes
        assigns(:input).should be_a(Input)
        assigns(:input).should be_persisted
      end

      it "redirects to the created input" do
        post :create, :input => valid_attributes
        response.should redirect_to(api_v1_input_path(Input.last))
      end
    end


    describe "first post of a monitoring device" do
      it "creates a new Input" do
        expect {
          post :create, { :water => 20.45, :solar => 12.34 }
        }.to change(Input, :count).by(2)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved input as @input" do
        # Trigger the behavior that occurs when invalid params are submitted
        Input.any_instance.stubs(:save).returns(false)
        post :create, :input => {}
        assigns(:input).should be_a_new(Input)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Input.any_instance.stubs(:save).returns(false)
        post :create, :input => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested input" do
        input = Input.create! valid_attributes
        # Assuming there are no other api_v1_inputs in the database, this
        # specifies that the Input created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Input.any_instance.expects(:update_attributes).with({'these' => 'params'})
        put :update, :id => input.id, :input => {'these' => 'params'}
      end

      it "assigns the requested input as @input" do
        input = Input.create! valid_attributes
        put :update, :id => input.id, :input => valid_attributes
        assigns(:input).should eq(input)
      end

      it "redirects to the input" do
        input = Input.create! valid_attributes
        put :update, :id => input.id, :input => valid_attributes
        response.should redirect_to(api_v1_input_path(input))
      end
    end

    describe "with invalid params" do
      it "assigns the input as @input" do
        input = Input.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Input.any_instance.stubs(:save).returns(false)
        put :update, :id => input.id.to_s, :input => {}
        assigns(:input).should eq(input)
      end

      it "re-renders the 'edit' template" do
        input = Input.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Input.any_instance.stubs(:save).returns(false)
        put :update, :id => input.id.to_s, :input => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested input" do
      input = Input.create! valid_attributes
      expect {
        delete :destroy, :id => input.id.to_s
      }.to change(Input, :count).by(-1)
    end

    it "redirects to the api_v1_inputs list" do
      input = Input.create! valid_attributes
      delete :destroy, :id => input.id.to_s
      response.should redirect_to(api_v1_inputs_url)
    end
  end

end
